
##Şifremi unuttum
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sifresifirladuzce@gmail.com
#spring.mail.password=lkwu hive bldj aiwq
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true