#MYSQL AYARLARI
mysql.driver=com.mysql.cj.jdbc.Driver
mysql.url=jdbc:mysql://localhost:3306/rehber_db?characterEncoding=utf-8
mysql.username=root
mysql.password=12345

#HIBERNATE AYARLARI
hibernate.show_sql=false
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update

# c3p0 ayarlari
hibernate.c3p0.min_size=5
hibernate.c3p0.max_size=200
hibernate.c3p0.initialPoolSize=5
hibernate.c3p0.acquire_increment=1
# bostaki baglantilar ne kadar tutulsun (sn)
hibernate.c3p0.timeout=1800
# cachelenecek sorgu sayisi
hibernate.c3p0.max_statements=150
# baglanti kontrol (ping) suresi (sn)
hibernate.c3p0.idle_test_period=60
hibernate.c3p0.acquireRetryAttempts=1
hibernate.c3p0.acquireRetryDelay=250